services:
  waltz:
    image: ghcr.io/finos/waltz:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: waltz
      POSTGRES_DB: waltz
      POSTGRES_PASSWORD: waltz
