# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: AppMap Analysis

on: 
  push:
    branches:
      - actions-test

permissions:
      contents: read
      actions: read
      checks: write
      pull-requests: write
  
jobs:
  test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: waltz
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:     
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: 'maven'

    - name: Cache Maven packages    
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2
        restore-keys: ${{ runner.os }}-m2
    
    - name: Install AppMap tools
      uses: getappmap/install-action@v1
      with:
        project-type: maven
        install-appmap-library: false

    - name: Build with Maven
      run: mvn -Dmaven.test.failure.ignore=true -B -ntp -s .build.settings.xml -Pbuild-postgres,waltz-postgres,integration-tests clean test;

    - name: Save AppMaps
      uses: actions/cache/save@v3
      if: always()
      with:
        path: waltz-service/tmp/appmap
        key: appmaps-${{ github.sha }}-${{ github.run_attempt }}
    
  analyze:
    if: always()
    needs: [test] 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Install AppMap tools
        id: install-appmap
        uses: getappmap/install-action@v1
        with:
          directory: waltz-service
          install-appmap-library: false

      - name: Restore AppMaps
        uses: actions/cache/restore@v3
        with:
          path: waltz-service/tmp/appmap
          key: appmaps-${{ github.sha }}-${{ github.run_attempt }}

      - name: Setup upterm session
        uses: lhotari/action-upterm@v1

      - name: Archive AppMaps
        if: github.event_name != 'pull_request'
        uses: getappmap/archive-action@v1
        with:
          directory: waltz-service

      - name: Analyze AppMaps
        uses: getappmap/analyze-action@v1
        if: github.event_name == 'pull_request'
        with:
          directory: waltz-service
          base-revision: ${{ github.event.pull_request.base.sha }}
          head-revision: ${{ github.event.pull_request.head.sha }}
